name: imas
description: "IMAS Application with SSL Pinning"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # HTTP & Networking
  dio: ^5.2.0
  http: ^1.1.0
  connectivity_plus: ^6.1.4
  network_info_plus: ^6.1.4

  # UI Components
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.7.0
  multi_select_flutter: ^4.1.3
  multi_dropdown: ^3.0.1
  step_progress_indicator: ^1.0.2
  quick_quiz_view: ^0.0.2
  google_fonts: ^6.2.1
  confetti: ^0.8.0

  # Storage & Security
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3

  # File Handling
  file_picker: ^8.1.4
  open_file: ^3.5.10
  flutter_downloader: ^1.11.8

  # Device & Permissions
  permission_handler: ^11.3.1
  device_info_plus: ^11.3.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  flutter_email_sender: ^6.0.3
  mailer: ^6.4.1
  fluttertoast: ^8.2.10

  # WebView
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5


  # Certificate Pinning
#  ssl_pinning_plugin: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imas1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/imas1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/white.png
    - assets/welcome1.jpg
    - assets/new9.jpg
    - assets/new10.jpg
    - assets/new11.jpg
    - assets/v4.png
